/*
================================================================================
FIPSAR Q1 2026 | 00_TRUNCATE_ALL.sql — Run FIRST
================================================================================*/
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;



TRUNCATE TABLE QA_FIPSAR_PHI_HUB.STAGING.STG_PROSPECT_INTAKE;
TRUNCATE TABLE QA_FIPSAR_PHI_HUB.PHI_CORE.PATIENT_IDENTITY_XREF;
TRUNCATE TABLE QA_FIPSAR_PHI_HUB.PHI_CORE.PHI_PROSPECT_MASTER;
TRUNCATE TABLE QA_FIPSAR_DW.BRONZE.BRZ_PROSPECT_MASTER;
TRUNCATE TABLE QA_FIPSAR_DW.SILVER.SLV_PROSPECT_MASTER;
TRUNCATE TABLE QA_FIPSAR_DW.GOLD.DIM_PROSPECT;
TRUNCATE TABLE QA_FIPSAR_DW.GOLD.DIM_SFMC_JOB;
TRUNCATE TABLE QA_FIPSAR_DW.GOLD.FACT_PROSPECT_INTAKE;
TRUNCATE TABLE QA_FIPSAR_DW.GOLD.FACT_SFMC_ENGAGEMENT;
TRUNCATE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_SENT;
TRUNCATE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_OPENS;
TRUNCATE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_CLICKS;
TRUNCATE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_BOUNCES;
TRUNCATE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_SPAM;
TRUNCATE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_UNSUBSCRIBES;
TRUNCATE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_PROSPECT_C;
TRUNCATE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_PROSPECT_C_HISTORY;
TRUNCATE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_PROSPECT_JOURNEY_DETAILS;
TRUNCATE TABLE QA_FIPSAR_AUDIT.PIPELINE_AUDIT.PIPELINE_RUN_LOG;
TRUNCATE TABLE QA_FIPSAR_AUDIT.PIPELINE_AUDIT.DQ_REJECTION_LOG;
TRUNCATE TABLE QA_FIPSAR_DW.GOLD.DIM_CHANNEL;
TRUNCATE TABLE QA_FIPSAR_DW.GOLD.DIM_GEOGRAPHY;
TRUNCATE TABLE QA_FIPSAR_DW.GOLD.DIM_ENGAGEMENT_TYPE;



--select * from QA_FIPSAR_PHI_HUB.STAGING.STG_PROSPECT_INTAKE;
-- select master_patient_id, count(1) from  QA_FIPSAR_DW.BRONZE.BRZ_PROSPECT_MASTER
-- group by 1;
-- select * from QA_FIPSAR_DW.SILVER.SLV_PROSPECT_MASTER ;
--select * from QA_FIPSAR_AUDIT.PIPELINE_AUDIT.DQ_REJECTION_LOG;
--select * from QA_FIPSAR_DW.GOLD.fact_sfmc_engagement;
--select * from QA_FIPSAR_AUDIT.PIPELINE_AUDIT.PIPELINE_RUN_LOG;
--select * from QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_SENT;

---------------
CREATE OR REPLACE SEQUENCE QA_FIPSAR_PHI_HUB.PHI_CORE.SEQ_MASTER_PATIENT_ID 
START = 801
INCREMENT = 1;



-- DIM_DATE: Regenerate if empty:
-- INSERT INTO QA_FIPSAR_DW.GOLD.DIM_DATE SELECT TO_NUMBER(TO_CHAR(dt,'YYYYMMDD')),dt,YEAR(dt),
-- QUARTER(dt),MONTH(dt),MONTHNAME(dt),WEEKOFYEAR(dt),DAY(dt),DAYOFWEEK(dt),DAYNAME(dt),
-- CASE WHEN DAYOFWEEK(dt) IN(0,6) THEN TRUE ELSE FALSE END
-- FROM(SELECT DATEADD(DAY,SEQ4(),'2025-01-01'::DATE)AS dt FROM TABLE(GENERATOR(ROWCOUNT=>1096)));
