/***********************************************************************
 *  FIPSAR – COMPLETE ACCOUNT DDL MIGRATION SCRIPT
 *  Generated: 2026-04-11
 *  Account:   ILB69694
 *  
 *  OBJECT INVENTORY (PROD + QA environments)
 *  ──────────────────────────────────────────
 *  Warehouses ................  2
 *  Storage Integrations ......  1
 *  Notification Integrations .  1
 *  Databases .................  10 (5 PROD + 5 QA)
 *  Schemas ...................  32 (excl. INFORMATION_SCHEMA / PUBLIC)
 *  Sequences .................  4
 *  File Formats ..............  10
 *  External Stages ...........  28
 *  Internal Stages ...........  2
 *  Tables ....................  52
 *  Views .....................  4
 *  Streams ...................  8
 *  Stored Procedures .........  62
 *  User-Defined Functions ....  1
 *  Tasks .....................  22
 *  Streamlit Apps ............  1
 *
 *  EXECUTION ORDER:
 *    1. Warehouses
 *    2. Storage Integration
 *    3. Notification Integration
 *    4. Databases & Schemas
 *    5. Sequences
 *    6. File Formats
 *    7. Stages (External + Internal)
 *    8. Tables
 *    9. Views
 *   10. Streams
 *   11. Stored Procedures
 *   12. User-Defined Functions
 *   13. Tasks
 *   14. Streamlit Apps (note only; requires UI deployment)
 ***********************************************************************/


-- =====================================================================
-- 1. WAREHOUSES
-- =====================================================================

CREATE OR REPLACE WAREHOUSE COMPUTE_WH
    WITH WAREHOUSE_SIZE      = 'X-Small'
    AUTO_SUSPEND             = 600
    AUTO_RESUME              = TRUE
    MIN_CLUSTER_COUNT        = 1
    MAX_CLUSTER_COUNT        = 1
    SCALING_POLICY           = 'STANDARD'
    INITIALLY_SUSPENDED      = FALSE;

-- SYSTEM$STREAMLIT_NOTEBOOK_WH is system-managed; included for completeness
CREATE WAREHOUSE IF NOT EXISTS SYSTEM$STREAMLIT_NOTEBOOK_WH
    WITH WAREHOUSE_SIZE      = 'X-Small'
    AUTO_SUSPEND             = 60
    AUTO_RESUME              = TRUE
    MIN_CLUSTER_COUNT        = 1
    MAX_CLUSTER_COUNT        = 10
    SCALING_POLICY           = 'STANDARD'
    INITIALLY_SUSPENDED      = TRUE;


-- =====================================================================
-- 2. STORAGE INTEGRATION
-- =====================================================================

CREATE OR REPLACE STORAGE INTEGRATION FIPSAR_S3_INTEGRATION
    TYPE                     = EXTERNAL_STAGE
    STORAGE_PROVIDER         = 'S3'
    STORAGE_AWS_ROLE_ARN     = 'arn:aws:iam::266931005008:role/fipsar-snowflake-s3-role-2'
    ENABLED                  = TRUE
    STORAGE_ALLOWED_LOCATIONS = ('s3://fipsar-salesforce/')
    COMMENT                  = 'S3 integration covering entire fipsar-salesforce bucket';


-- =====================================================================
-- 3. NOTIFICATION INTEGRATION
-- =====================================================================

CREATE OR REPLACE NOTIFICATION INTEGRATION FIPSAR_EMAIL_NOTIFICATION
    TYPE            = EMAIL
    ENABLED         = TRUE
    ALLOWED_RECIPIENTS = ('akileshvishnu103@gmail.com')
    COMMENT         = 'Pipeline notifications — both admin emails';


-- =====================================================================
-- 4. DATABASES & SCHEMAS
-- =====================================================================

-- ── PROD ─────────────────────────────────────────────────────────────

CREATE OR REPLACE DATABASE FIPSAR_PHI_HUB
    COMMENT = 'PHI Hub: patient identity, staging, core PHI tables';
CREATE SCHEMA IF NOT EXISTS FIPSAR_PHI_HUB.STAGING
    COMMENT = 'S3 CSV landing area';
CREATE SCHEMA IF NOT EXISTS FIPSAR_PHI_HUB.PHI_CORE
    COMMENT = 'Core PHI tables with MASTER_PATIENT_ID';

CREATE OR REPLACE DATABASE FIPSAR_DW
    COMMENT = 'Data Warehouse: Bronze / Silver / Gold layers';
CREATE SCHEMA IF NOT EXISTS FIPSAR_DW.BRONZE
    COMMENT = 'Raw append-only copies from PHI';
CREATE SCHEMA IF NOT EXISTS FIPSAR_DW.SILVER
    COMMENT = 'Data quality gated layer';
CREATE SCHEMA IF NOT EXISTS FIPSAR_DW.GOLD
    COMMENT = 'Star schema for reporting and AI';

CREATE OR REPLACE DATABASE FIPSAR_SFMC_EVENTS
    COMMENT = 'SFMC return-file ingestion: sends, opens, clicks, bounces, etc.';
CREATE SCHEMA IF NOT EXISTS FIPSAR_SFMC_EVENTS.RAW_EVENTS
    COMMENT = 'Raw SFMC event CSV landing';

CREATE OR REPLACE DATABASE FIPSAR_AI
    COMMENT = 'AI synthetic data, feature tables, semantic models';
CREATE SCHEMA IF NOT EXISTS FIPSAR_AI.AI_SYNTHETIC_DATA
    COMMENT = 'Synthetic data for AI development';
CREATE SCHEMA IF NOT EXISTS FIPSAR_AI.AI_FEATURES
    COMMENT = 'Feature tables for ML models';
CREATE SCHEMA IF NOT EXISTS FIPSAR_AI.AI_SEMANTIC
    COMMENT = 'Semantic views for model consumption';
CREATE SCHEMA IF NOT EXISTS FIPSAR_AI.AI_PIPELINES;

CREATE OR REPLACE DATABASE FIPSAR_AUDIT
    COMMENT = 'Pipeline audit and data quality logging';
CREATE SCHEMA IF NOT EXISTS FIPSAR_AUDIT.PIPELINE_AUDIT
    COMMENT = 'Pipeline logs and DQ tracking';

-- ── QA ───────────────────────────────────────────────────────────────

CREATE OR REPLACE DATABASE QA_FIPSAR_PHI_HUB
    COMMENT = 'PHI Hub: patient identity, staging, core PHI tables';
CREATE SCHEMA IF NOT EXISTS QA_FIPSAR_PHI_HUB.STAGING
    COMMENT = 'S3 CSV landing area';
CREATE SCHEMA IF NOT EXISTS QA_FIPSAR_PHI_HUB.PHI_CORE
    COMMENT = 'Core PHI tables with MASTER_PATIENT_ID';

CREATE OR REPLACE DATABASE QA_FIPSAR_DW
    COMMENT = 'Data Warehouse: Bronze / Silver / Gold layers';
CREATE SCHEMA IF NOT EXISTS QA_FIPSAR_DW.BRONZE
    COMMENT = 'Raw append-only copies from PHI';
CREATE SCHEMA IF NOT EXISTS QA_FIPSAR_DW.SILVER
    COMMENT = 'Data quality gated layer';
CREATE SCHEMA IF NOT EXISTS QA_FIPSAR_DW.GOLD
    COMMENT = 'Star schema for reporting and AI';

CREATE OR REPLACE DATABASE QA_FIPSAR_SFMC_EVENTS
    COMMENT = 'SFMC return-file ingestion: sends, opens, clicks, bounces, etc.';
CREATE SCHEMA IF NOT EXISTS QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS
    COMMENT = 'Raw SFMC event CSV landing';

CREATE OR REPLACE DATABASE QA_FIPSAR_AI
    COMMENT = 'AI synthetic data, feature tables, semantic models';
CREATE SCHEMA IF NOT EXISTS QA_FIPSAR_AI.AI_SYNTHETIC_DATA
    COMMENT = 'Synthetic data for AI development';
CREATE SCHEMA IF NOT EXISTS QA_FIPSAR_AI.AI_FEATURES
    COMMENT = 'Feature tables for ML models';
CREATE SCHEMA IF NOT EXISTS QA_FIPSAR_AI.AI_SEMANTIC
    COMMENT = 'Semantic views for model consumption';
CREATE SCHEMA IF NOT EXISTS QA_FIPSAR_AI.AI_PIPELINES;

CREATE OR REPLACE DATABASE QA_FIPSAR_AUDIT
    COMMENT = 'Pipeline audit and data quality logging';
CREATE SCHEMA IF NOT EXISTS QA_FIPSAR_AUDIT.PIPELINE_AUDIT
    COMMENT = 'Pipeline logs and DQ tracking';


-- =====================================================================
-- 5. SEQUENCES
-- =====================================================================

CREATE OR REPLACE SEQUENCE FIPSAR_PHI_HUB.PHI_CORE.SEQ_MASTER_PATIENT_ID
    START = 1901 INCREMENT = 1;

CREATE OR REPLACE SEQUENCE FIPSAR_DW.BRONZE.SEQ_MASTER_PATIENT_ID
    START = 801 INCREMENT = 1
    COMMENT = 'Generates FIP + 10-digit zero-padded IDs';

CREATE OR REPLACE SEQUENCE QA_FIPSAR_PHI_HUB.PHI_CORE.SEQ_MASTER_PATIENT_ID
    START = 1901 INCREMENT = 1;

CREATE OR REPLACE SEQUENCE QA_FIPSAR_DW.BRONZE.SEQ_MASTER_PATIENT_ID
    START = 801 INCREMENT = 1
    COMMENT = 'Generates FIP + 10-digit zero-padded IDs';


-- =====================================================================
-- 6. FILE FORMATS
-- =====================================================================

-- ── PROD ─────────────────────────────────────────────────────────────

CREATE OR REPLACE FILE FORMAT FIPSAR_PHI_HUB.STAGING.FF_PROSPECT_CSV
    TYPE                         = 'CSV'
    FIELD_DELIMITER              = ','
    RECORD_DELIMITER             = '\n'
    SKIP_HEADER                  = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF                      = ('', 'NULL', 'null')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    EMPTY_FIELD_AS_NULL          = TRUE
    MULTI_LINE                   = TRUE;

CREATE OR REPLACE FILE FORMAT FIPSAR_PHI_HUB.STAGING.FF_SFMC_EVENT_CSV
    TYPE                         = 'CSV'
    FIELD_DELIMITER              = ','
    RECORD_DELIMITER             = '\n'
    SKIP_HEADER                  = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF                      = ('', 'NULL', 'null')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    EMPTY_FIELD_AS_NULL          = TRUE
    MULTI_LINE                   = TRUE;

CREATE OR REPLACE FILE FORMAT FIPSAR_SFMC_EVENTS.RAW_EVENTS.FF_SFMC_CSV_UTF8
    TYPE                         = 'CSV'
    FIELD_DELIMITER              = ','
    RECORD_DELIMITER             = '\n'
    SKIP_HEADER                  = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ESCAPE_UNENCLOSED_FIELD      = 'NONE'
    TRIM_SPACE                   = TRUE
    NULL_IF                      = ('NULL', 'null', '')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    EMPTY_FIELD_AS_NULL          = TRUE
    ENCODING                     = 'UTF8'
    MULTI_LINE                   = TRUE;

CREATE OR REPLACE FILE FORMAT FIPSAR_SFMC_EVENTS.RAW_EVENTS.FF_SFMC_CSV_UTF16
    TYPE                         = 'CSV'
    FIELD_DELIMITER              = ','
    RECORD_DELIMITER             = '\n'
    SKIP_HEADER                  = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ESCAPE_UNENCLOSED_FIELD      = 'NONE'
    TRIM_SPACE                   = TRUE
    NULL_IF                      = ('NULL', 'null', '')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    EMPTY_FIELD_AS_NULL          = TRUE
    ENCODING                     = 'UTF16LE'
    MULTI_LINE                   = TRUE;

CREATE OR REPLACE FILE FORMAT FIPSAR_AI.AI_SYNTHETIC_DATA.CSV_FORMAT
    TYPE                         = 'CSV'
    FIELD_DELIMITER              = ','
    RECORD_DELIMITER             = '\n'
    SKIP_HEADER                  = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE                   = TRUE
    NULL_IF                      = ('', 'NULL', 'null', 'None')
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    EMPTY_FIELD_AS_NULL          = TRUE
    MULTI_LINE                   = TRUE;

-- ── QA ───────────────────────────────────────────────────────────────

CREATE OR REPLACE FILE FORMAT QA_FIPSAR_PHI_HUB.STAGING.FF_PROSPECT_CSV
    TYPE                         = 'CSV'
    FIELD_DELIMITER              = ','
    RECORD_DELIMITER             = '\n'
    SKIP_HEADER                  = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF                      = ('', 'NULL', 'null')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    EMPTY_FIELD_AS_NULL          = TRUE
    MULTI_LINE                   = TRUE;

CREATE OR REPLACE FILE FORMAT QA_FIPSAR_PHI_HUB.STAGING.FF_SFMC_EVENT_CSV
    TYPE                         = 'CSV'
    FIELD_DELIMITER              = ','
    RECORD_DELIMITER             = '\n'
    SKIP_HEADER                  = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF                      = ('', 'NULL', 'null')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    EMPTY_FIELD_AS_NULL          = TRUE
    MULTI_LINE                   = TRUE;

CREATE OR REPLACE FILE FORMAT QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.FF_SFMC_CSV_UTF8
    TYPE                         = 'CSV'
    FIELD_DELIMITER              = ','
    RECORD_DELIMITER             = '\n'
    SKIP_HEADER                  = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ESCAPE_UNENCLOSED_FIELD      = 'NONE'
    TRIM_SPACE                   = TRUE
    NULL_IF                      = ('NULL', 'null', '')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    EMPTY_FIELD_AS_NULL          = TRUE
    ENCODING                     = 'UTF8'
    MULTI_LINE                   = TRUE;

CREATE OR REPLACE FILE FORMAT QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.FF_SFMC_CSV_UTF16
    TYPE                         = 'CSV'
    FIELD_DELIMITER              = ','
    RECORD_DELIMITER             = '\n'
    SKIP_HEADER                  = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    ESCAPE_UNENCLOSED_FIELD      = 'NONE'
    TRIM_SPACE                   = TRUE
    NULL_IF                      = ('NULL', 'null', '')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    EMPTY_FIELD_AS_NULL          = TRUE
    ENCODING                     = 'UTF16LE'
    MULTI_LINE                   = TRUE;

CREATE OR REPLACE FILE FORMAT QA_FIPSAR_AI.AI_SYNTHETIC_DATA.CSV_FORMAT
    TYPE                         = 'CSV'
    FIELD_DELIMITER              = ','
    RECORD_DELIMITER             = '\n'
    SKIP_HEADER                  = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE                   = TRUE
    NULL_IF                      = ('', 'NULL', 'null', 'None')
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    EMPTY_FIELD_AS_NULL          = TRUE
    MULTI_LINE                   = TRUE;


-- =====================================================================
-- 7. STAGES
-- =====================================================================

-- ── PROD External Stages ─────────────────────────────────────────────

CREATE OR REPLACE STAGE FIPSAR_PHI_HUB.STAGING.STG_PROSPECT_INBOUND
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/Prospects-Patients-Campaign/inbound/'
    COMMENT = 'Prospect intake CSVs from Lambda / API';

CREATE OR REPLACE STAGE FIPSAR_PHI_HUB.STAGING.STG_SFMC_OUTBOUND
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/Snowflake-to-SFMC-Patient-Prospects/Prospect_delta/'
    COMMENT = 'Outbound prospect delta files for SFMC';

CREATE OR REPLACE STAGE FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_SENT_DE
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-Events/Sent_DE/'
    COMMENT = 'SFMC Sent event files';

CREATE OR REPLACE STAGE FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_UNSUBSCRIBE_DE
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-Events/Unsubscribe_DE/'
    COMMENT = 'SFMC Unsubscribe event files';

CREATE OR REPLACE STAGE FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_JOURNEY_ACTIVITY_DE
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-Events/JourneyActivity_DE/'
    COMMENT = 'SFMC Journey Activity export files';

CREATE OR REPLACE STAGE FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_OPEN_DE
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-Events/Open_DE/'
    COMMENT = 'SFMC Open event files';

CREATE OR REPLACE STAGE FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_CLICK_DE
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-Events/Click_DE/'
    COMMENT = 'SFMC Click event files';

CREATE OR REPLACE STAGE FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_BOUNCE_DE
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-Events/Bounce_DE/'
    COMMENT = 'SFMC Bounce event files';

CREATE OR REPLACE STAGE FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_JOB_DE
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-Events/Job_DE/'
    COMMENT = 'SFMC Job export files';

CREATE OR REPLACE STAGE FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_PROSPECT_C_HISTORY
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-History/Prospect_c_history/'
    COMMENT = 'SFMC Prospect_c_history files';

CREATE OR REPLACE STAGE FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_PROSPECT_C
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-History/Prospect_c/'
    COMMENT = 'SFMC Prospect_c current snapshot files';

CREATE OR REPLACE STAGE FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_PROSPECT_JOURNEY_DETAILS
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-History/Prospect_journey_details/'
    COMMENT = 'SFMC Prospect journey details files';

CREATE OR REPLACE STAGE FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_EVENTS_INBOUND
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-SNowflake-Events/inbound/'
    COMMENT = 'Legacy shared inbound stage (kept for backward compat)';

-- ── PROD Internal Stages ─────────────────────────────────────────────

CREATE OR REPLACE STAGE FIPSAR_AI.AI_SYNTHETIC_DATA.CSV_UPLOAD_STAGE
    COMMENT = 'Upload training/test CSVs here';

CREATE OR REPLACE STAGE FIPSAR_AI.AI_SEMANTIC.CORTEX_ANALYST_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Upload fipsar_semantic_gokul.yaml here';

-- ── QA External Stages ───────────────────────────────────────────────

CREATE OR REPLACE STAGE QA_FIPSAR_PHI_HUB.STAGING.STG_PROSPECT_INBOUND
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/Prospects-Patients-Campaign/inbound/'
    COMMENT = 'Prospect intake CSVs from Lambda / API';

CREATE OR REPLACE STAGE QA_FIPSAR_PHI_HUB.STAGING.STG_SFMC_OUTBOUND
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/Snowflake-to-SFMC-Patient-Prospects/Prospect_delta/'
    COMMENT = 'Outbound prospect delta files for SFMC';

CREATE OR REPLACE STAGE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_SENT_DE
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-Events/Sent_DE/'
    COMMENT = 'SFMC Sent event files';

CREATE OR REPLACE STAGE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_UNSUBSCRIBE_DE
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-Events/Unsubscribe_DE/'
    COMMENT = 'SFMC Unsubscribe event files';

CREATE OR REPLACE STAGE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_JOURNEY_ACTIVITY_DE
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-Events/JourneyActivity_DE/'
    COMMENT = 'SFMC Journey Activity export files';

CREATE OR REPLACE STAGE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_OPEN_DE
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-Events/Open_DE/'
    COMMENT = 'SFMC Open event files';

CREATE OR REPLACE STAGE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_CLICK_DE
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-Events/Click_DE/'
    COMMENT = 'SFMC Click event files';

CREATE OR REPLACE STAGE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_BOUNCE_DE
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-Events/Bounce_DE/'
    COMMENT = 'SFMC Bounce event files';

CREATE OR REPLACE STAGE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_JOB_DE
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-Events/Job_DE/'
    COMMENT = 'SFMC Job export files';

CREATE OR REPLACE STAGE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_PROSPECT_C_HISTORY
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-History/Prospect_c_history/'
    COMMENT = 'SFMC Prospect_c_history files';

CREATE OR REPLACE STAGE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_PROSPECT_C
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-History/Prospect_c/'
    COMMENT = 'SFMC Prospect_c current snapshot files';

CREATE OR REPLACE STAGE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_PROSPECT_JOURNEY_DETAILS
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-Snowflake-History/Prospect_journey_details/'
    COMMENT = 'SFMC Prospect journey details files';

CREATE OR REPLACE STAGE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.STG_SFMC_EVENTS_INBOUND
    STORAGE_INTEGRATION = FIPSAR_S3_INTEGRATION
    URL = 's3://fipsar-salesforce/SFMC/SFMC-to-SNowflake-Events/inbound/'
    COMMENT = 'Legacy shared inbound stage (kept for backward compat)';


-- =====================================================================
-- 8. TABLES
-- =====================================================================

-- ── FIPSAR_PHI_HUB.STAGING ──────────────────────────────────────────

CREATE OR REPLACE TABLE FIPSAR_PHI_HUB.STAGING.STG_PROSPECT_INTAKE (
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE_NUMBER VARCHAR(20),
    AGE VARCHAR(10),
    ADDRESS VARCHAR(255),
    APARTMENT_NO VARCHAR(50),
    CITY VARCHAR(100),
    STATE VARCHAR(2),
    ZIP_CODE VARCHAR(10),
    PATIENT_CONSENT VARCHAR(10),
    CHANNEL VARCHAR(50),
    SUBMISSION_TIMESTAMP VARCHAR(30),
    FILE_DATE VARCHAR(10),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE VARCHAR(500)
);

-- ── FIPSAR_PHI_HUB.PHI_CORE ────────────────────────────────────────

CREATE OR REPLACE TABLE FIPSAR_PHI_HUB.PHI_CORE.PATIENT_IDENTITY_XREF (
    MASTER_PATIENT_ID VARCHAR(13) NOT NULL,
    IDENTITY_KEY VARCHAR(600) NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_IDENTITY_XREF PRIMARY KEY (IDENTITY_KEY)
);

CREATE OR REPLACE TABLE FIPSAR_PHI_HUB.PHI_CORE.PHI_PROSPECT_MASTER (
    RECORD_ID VARCHAR(50) NOT NULL DEFAULT UUID_STRING(),
    MASTER_PATIENT_ID VARCHAR(13) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    AGE NUMBER(38,0),
    ADDRESS VARCHAR(255),
    APARTMENT_NO VARCHAR(50),
    CITY VARCHAR(100),
    STATE VARCHAR(2),
    ZIP_CODE VARCHAR(10),
    PATIENT_CONSENT BOOLEAN,
    CHANNEL VARCHAR(50),
    SUBMISSION_TIMESTAMP TIMESTAMP_NTZ(9),
    FILE_DATE DATE NOT NULL,
    PHI_LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CONSTRAINT PK_PHI_PROSPECT PRIMARY KEY (RECORD_ID)
);

-- ── FIPSAR_DW.BRONZE ───────────────────────────────────────────────

CREATE OR REPLACE TABLE FIPSAR_DW.BRONZE.BRZ_PROSPECT_MASTER (
    RECORD_ID VARCHAR(50),
    MASTER_PATIENT_ID VARCHAR(13),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE_NUMBER VARCHAR(20),
    AGE NUMBER(38,0),
    ADDRESS VARCHAR(255),
    APARTMENT_NO VARCHAR(50),
    CITY VARCHAR(100),
    STATE VARCHAR(2),
    ZIP_CODE VARCHAR(10),
    PATIENT_CONSENT BOOLEAN,
    CHANNEL VARCHAR(50),
    SUBMISSION_TIMESTAMP TIMESTAMP_NTZ(9),
    FILE_DATE DATE,
    PHI_LOADED_AT TIMESTAMP_NTZ(9),
    IS_ACTIVE BOOLEAN,
    BRONZE_LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_LAYER VARCHAR(20) DEFAULT 'PHI_HUB'
);

-- ── FIPSAR_DW.SILVER ───────────────────────────────────────────────

CREATE OR REPLACE TABLE FIPSAR_DW.SILVER.SLV_PROSPECT_MASTER (
    SLV_KEY NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    RECORD_ID VARCHAR(50),
    MASTER_PATIENT_ID VARCHAR(13) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    AGE NUMBER(38,0),
    ADDRESS VARCHAR(255),
    APARTMENT_NO VARCHAR(50),
    CITY VARCHAR(100),
    STATE VARCHAR(2),
    ZIP_CODE VARCHAR(10),
    PATIENT_CONSENT BOOLEAN,
    CHANNEL VARCHAR(50),
    SUBMISSION_TIMESTAMP TIMESTAMP_NTZ(9),
    FILE_DATE DATE,
    PHI_LOADED_AT TIMESTAMP_NTZ(9),
    IS_ACTIVE BOOLEAN,
    EFF_START_DATE DATE NOT NULL,
    EFF_END_DATE DATE NOT NULL DEFAULT CAST('9999-12-31' AS DATE),
    IS_CURRENT BOOLEAN NOT NULL DEFAULT TRUE,
    VERSION_NUM NUMBER(38,0) NOT NULL DEFAULT 1,
    DQ_PASSED BOOLEAN DEFAULT TRUE,
    SILVER_LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ── FIPSAR_DW.GOLD ─────────────────────────────────────────────────

CREATE OR REPLACE TABLE FIPSAR_DW.GOLD.DIM_CHANNEL (
    CHANNEL_KEY NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    CHANNEL_NAME VARCHAR(50) NOT NULL,
    CHANNEL_CATEGORY VARCHAR(50),
    CONSTRAINT PK_DIM_CHANNEL PRIMARY KEY (CHANNEL_KEY)
);

CREATE OR REPLACE TABLE FIPSAR_DW.GOLD.DIM_DATE (
    DATE_KEY NUMBER(38,0) NOT NULL,
    FULL_DATE DATE NOT NULL,
    YEAR NUMBER(38,0),
    QUARTER NUMBER(38,0),
    MONTH NUMBER(38,0),
    MONTH_NAME VARCHAR(20),
    WEEK_OF_YEAR NUMBER(38,0),
    DAY_OF_MONTH NUMBER(38,0),
    DAY_OF_WEEK NUMBER(38,0),
    DAY_NAME VARCHAR(20),
    IS_WEEKEND BOOLEAN,
    CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_KEY)
);

CREATE OR REPLACE TABLE FIPSAR_DW.GOLD.DIM_ENGAGEMENT_TYPE (
    EVENT_TYPE_KEY NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    EVENT_CATEGORY VARCHAR(50),
    IS_POSITIVE BOOLEAN,
    CONSTRAINT PK_DIM_ET PRIMARY KEY (EVENT_TYPE_KEY)
);

CREATE OR REPLACE TABLE FIPSAR_DW.GOLD.DIM_GEOGRAPHY (
    GEO_KEY NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    CITY VARCHAR(100),
    STATE VARCHAR(2),
    ZIP_CODE VARCHAR(10),
    REGION VARCHAR(50),
    CONSTRAINT PK_DIM_GEO PRIMARY KEY (GEO_KEY)
);

CREATE OR REPLACE TABLE FIPSAR_DW.GOLD.DIM_PROSPECT (
    PROSPECT_KEY NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    MASTER_PATIENT_ID VARCHAR(13) NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE_NUMBER VARCHAR(20),
    AGE NUMBER(38,0),
    AGE_GROUP VARCHAR(20),
    CITY VARCHAR(100),
    STATE VARCHAR(2),
    ZIP_CODE VARCHAR(10),
    PATIENT_CONSENT BOOLEAN,
    FIRST_INTAKE_DATE DATE,
    LAST_INTAKE_DATE DATE,
    INTAKE_COUNT NUMBER(38,0) DEFAULT 1,
    PRIMARY_CHANNEL VARCHAR(50),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_DIM_PROSPECT UNIQUE (MASTER_PATIENT_ID),
    CONSTRAINT PK_DIM_PROSPECT PRIMARY KEY (PROSPECT_KEY)
);

CREATE OR REPLACE TABLE FIPSAR_DW.GOLD.DIM_SFMC_JOB (
    JOB_KEY NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    JOB_ID NUMBER(38,0) NOT NULL,
    JOURNEY_TYPE VARCHAR(50),
    MAPPED_STAGE VARCHAR(100),
    EMAIL_NAME VARCHAR(200),
    EMAIL_SUBJECT VARCHAR(500),
    RECORD_TYPE VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_DIM_JOB_ID UNIQUE (JOB_ID),
    CONSTRAINT PK_DIM_SFMC_JOB PRIMARY KEY (JOB_KEY)
);

CREATE OR REPLACE TABLE FIPSAR_DW.GOLD.FACT_PROSPECT_INTAKE (
    INTAKE_KEY NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    RECORD_ID VARCHAR(50),
    MASTER_PATIENT_ID VARCHAR(13),
    PROSPECT_KEY NUMBER(38,0),
    CHANNEL_KEY NUMBER(38,0),
    DATE_KEY NUMBER(38,0),
    GEO_KEY NUMBER(38,0),
    SUBMISSION_TIMESTAMP TIMESTAMP_NTZ(9),
    FILE_DATE DATE,
    AGE NUMBER(38,0),
    CONSENT_FLAG NUMBER(38,0),
    GOLD_LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_FACT_INTAKE PRIMARY KEY (INTAKE_KEY)
);

CREATE OR REPLACE TABLE FIPSAR_DW.GOLD.FACT_SFMC_ENGAGEMENT (
    FACT_ENGAGEMENT_KEY NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    SUBSCRIBER_KEY VARCHAR(100),
    MASTER_PATIENT_ID VARCHAR(13),
    PROSPECT_KEY NUMBER(38,0),
    JOB_KEY NUMBER(38,0),
    EVENT_TYPE_KEY NUMBER(38,0),
    DATE_KEY NUMBER(38,0),
    EVENT_TIMESTAMP TIMESTAMP_NTZ(9),
    EVENT_TYPE VARCHAR(50),
    DOMAIN VARCHAR(255),
    IS_UNIQUE BOOLEAN,
    BOUNCE_CATEGORY VARCHAR(100),
    BOUNCE_TYPE VARCHAR(100),
    CLICK_URL VARCHAR(2000),
    REASON VARCHAR(500),
    ACCOUNT_ID VARCHAR(20),
    JOB_ID NUMBER(38,0),
    RECORD_TYPE VARCHAR(50),
    SOURCE_FILE_NAME VARCHAR(1000),
    LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    IS_SUPPRESSED BOOLEAN DEFAULT FALSE,
    SUPPRESSION_REASON VARCHAR(500),
    CONSTRAINT PK_FACT_ENGAGEMENT PRIMARY KEY (FACT_ENGAGEMENT_KEY)
);

-- ── FIPSAR_SFMC_EVENTS.RAW_EVENTS ──────────────────────────────────

CREATE OR REPLACE TABLE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_SENT (
    ACCOUNT_ID VARCHAR(50),
    OYB_ACCOUNT_ID VARCHAR(50),
    JOB_ID NUMBER(38,0),
    LIST_ID NUMBER(38,0),
    BATCH_ID NUMBER(38,0),
    SUBSCRIBER_ID NUMBER(38,0),
    SUBSCRIBER_KEY VARCHAR(100),
    EVENT_DATE VARCHAR(100),
    DOMAIN VARCHAR(255),
    TRIGGERED_SEND_CUSTOMER_KEY VARCHAR(255),
    TRIGGERED_SEND_DEF_OBJECT_ID VARCHAR(255),
    RECORD_TYPE VARCHAR(50),
    _SOURCE_FILE_NAME VARCHAR(1000),
    _SOURCE_ROW_NUMBER NUMBER(38,0),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_OPENS (
    ACCOUNT_ID VARCHAR(50),
    OYB_ACCOUNT_ID VARCHAR(50),
    JOB_ID NUMBER(38,0),
    LIST_ID NUMBER(38,0),
    BATCH_ID NUMBER(38,0),
    SUBSCRIBER_ID NUMBER(38,0),
    SUBSCRIBER_KEY VARCHAR(100),
    EVENT_DATE VARCHAR(100),
    DOMAIN VARCHAR(255),
    IS_UNIQUE VARCHAR(20),
    TRIGGERED_SEND_CUSTOMER_KEY VARCHAR(255),
    TRIGGERED_SEND_DEF_OBJECT_ID VARCHAR(255),
    RECORD_TYPE VARCHAR(50),
    _SOURCE_FILE_NAME VARCHAR(1000),
    _SOURCE_ROW_NUMBER NUMBER(38,0),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_CLICKS (
    ACCOUNT_ID VARCHAR(50),
    OYB_ACCOUNT_ID VARCHAR(50),
    JOB_ID NUMBER(38,0),
    LIST_ID NUMBER(38,0),
    BATCH_ID NUMBER(38,0),
    SUBSCRIBER_ID NUMBER(38,0),
    SUBSCRIBER_KEY VARCHAR(100),
    EVENT_DATE VARCHAR(100),
    DOMAIN VARCHAR(255),
    URL VARCHAR(2000),
    LINK_NAME VARCHAR(1000),
    LINK_CONTENT VARCHAR(2000),
    IS_UNIQUE VARCHAR(20),
    TRIGGERED_SEND_DEF_OBJECT_ID VARCHAR(255),
    TRIGGERED_SEND_CUSTOMER_KEY VARCHAR(255),
    RECORD_TYPE VARCHAR(50),
    _SOURCE_FILE_NAME VARCHAR(1000),
    _SOURCE_ROW_NUMBER NUMBER(38,0),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_BOUNCES (
    ACCOUNT_ID VARCHAR(50),
    OYB_ACCOUNT_ID VARCHAR(50),
    JOB_ID NUMBER(38,0),
    LIST_ID NUMBER(38,0),
    BATCH_ID NUMBER(38,0),
    SUBSCRIBER_ID NUMBER(38,0),
    SUBSCRIBER_KEY VARCHAR(100),
    EVENT_DATE VARCHAR(100),
    DOMAIN VARCHAR(255),
    BOUNCE_CATEGORY VARCHAR(255),
    BOUNCE_TYPE VARCHAR(255),
    SMTP_BOUNCE_REASON VARCHAR(2000),
    TRIGGERED_SEND_CUSTOMER_KEY VARCHAR(255),
    TRIGGERED_SEND_DEF_OBJECT_ID VARCHAR(255),
    RECORD_TYPE VARCHAR(50),
    _SOURCE_FILE_NAME VARCHAR(1000),
    _SOURCE_ROW_NUMBER NUMBER(38,0),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_UNSUBSCRIBES (
    ACCOUNT_ID VARCHAR(50),
    SUBSCRIBER_KEY VARCHAR(100),
    JOB_ID NUMBER(38,0),
    EVENT_DATE VARCHAR(100),
    REASON VARCHAR(2000),
    RECORD_TYPE VARCHAR(50),
    _SOURCE_FILE_NAME VARCHAR(1000),
    _SOURCE_ROW_NUMBER NUMBER(38,0),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_SPAM (
    ACCOUNT_ID VARCHAR(50),
    SUBSCRIBER_KEY VARCHAR(100),
    JOB_ID NUMBER(38,0),
    EVENT_DATE VARCHAR(100),
    COMPLAINT_TYPE VARCHAR(255),
    RECORD_TYPE VARCHAR(50),
    _SOURCE_FILE_NAME VARCHAR(1000),
    _SOURCE_ROW_NUMBER NUMBER(38,0),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_JOB_METADATA (
    JOB_ID NUMBER(38,0),
    JOURNEY_TYPE VARCHAR(255),
    MAPPED_STAGE VARCHAR(255),
    EMAIL_NAME VARCHAR(500),
    EMAIL_SUBJECT VARCHAR(1000),
    RECORD_TYPE VARCHAR(50),
    _SOURCE_FILE_NAME VARCHAR(1000),
    _SOURCE_ROW_NUMBER NUMBER(38,0),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_PROSPECT_C (
    PROSPECT_ID VARCHAR(16777216),
    FIRST_NAME VARCHAR(16777216),
    LAST_NAME VARCHAR(16777216),
    EMAIL_ADDRESS VARCHAR(16777216),
    MARKETING_CONSENT VARCHAR(16777216),
    HIGH_ENGAGEMENT VARCHAR(16777216),
    REGISTRATION_DATE VARCHAR(16777216),
    LAST_UPDATED VARCHAR(16777216),
    _SOURCE_FILE_NAME VARCHAR(1000),
    _SOURCE_ROW_NUMBER NUMBER(38,0),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_PROSPECT_C_HISTORY (
    PROSPECT_ID VARCHAR(16777216),
    FIRST_NAME VARCHAR(16777216),
    LAST_NAME VARCHAR(16777216),
    EMAIL_ADDRESS VARCHAR(16777216),
    MARKETING_CONSENT VARCHAR(16777216),
    HIGH_ENGAGEMENT VARCHAR(16777216),
    REGISTRATION_DATE VARCHAR(16777216),
    BATCH_ID VARCHAR(16777216),
    JOB_ID VARCHAR(16777216),
    LAST_UPDATED VARCHAR(16777216),
    _SOURCE_FILE_NAME VARCHAR(1000),
    _SOURCE_ROW_NUMBER NUMBER(38,0),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_PROSPECT_JOURNEY_DETAILS (
    PROSPECT_ID VARCHAR(16777216),
    WELCOME_JOURNEY_COMPLETE VARCHAR(16777216),
    NURTURE_JOURNEY_COMPLETE VARCHAR(16777216),
    SUPPRESSION_FLAG VARCHAR(16777216),
    WELCOMEJOURNEY_WELCOMEEMAIL_SENT VARCHAR(16777216),
    WELCOMEJOURNEY_WELCOMEEMAIL_SENT_DATE VARCHAR(16777216),
    WELCOMEJOURNEY_EDUCATIONEMAIL_SENT VARCHAR(16777216),
    WELCOMEJOURNEY_EDUCATIONEMAIL_SENT_DATE VARCHAR(16777216),
    NURTUREJOURNEY_EDUCATIONEMAIL1_SENT VARCHAR(16777216),
    NURTUREJOURNEY_EDUCATIONEMAIL1_SENT_DATE VARCHAR(16777216),
    NURTUREJOURNEY_EDUCATIONEMAIL2_SENT VARCHAR(16777216),
    NURTUREJOURNEY_EDUCATIONEMAIL2_SENT_DATE VARCHAR(16777216),
    NURTUREJOURNEY_PROSPECTSTORYEMAIL_SENT VARCHAR(16777216),
    NURTUREJOURNEY_PROSPECTSTORYEMAIL_SENT_DATE VARCHAR(16777216),
    HIGHENGAGEMENT_CONVERSIONEMAIL_SENT VARCHAR(16777216),
    HIGHENGAGEMENT_CONVERSIONEMAIL_SENT_DATE VARCHAR(16777216),
    HIGHENGAGEMENT_REMINDEREMAIL_SENT VARCHAR(16777216),
    HIGHENGAGEMENT_REMINDEREMAIL_SENT_DATE VARCHAR(16777216),
    _SOURCE_FILE_NAME VARCHAR(1000),
    _SOURCE_ROW_NUMBER NUMBER(38,0),
    _LOADED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ── FIPSAR_AI.AI_FEATURES ──────────────────────────────────────────

CREATE OR REPLACE TABLE FIPSAR_AI.AI_FEATURES.FEAT_UCA_PROSPECT_360 (
    MASTER_PATIENT_ID VARCHAR(20) NOT NULL,
    AGE NUMBER(38,0),
    AGE_GROUP VARCHAR(20),
    STATE VARCHAR(10),
    REGION VARCHAR(50),
    PRIMARY_CHANNEL VARCHAR(50),
    INTAKE_COUNT NUMBER(38,0),
    DAYS_SINCE_FIRST_INTAKE NUMBER(38,0),
    TOTAL_SENDS NUMBER(38,0),
    TOTAL_OPENS NUMBER(38,0),
    TOTAL_CLICKS NUMBER(38,0),
    TOTAL_BOUNCES NUMBER(38,0),
    TOTAL_UNSUBS NUMBER(38,0),
    OPEN_RATE FLOAT,
    CLICK_TO_OPEN_RATE FLOAT,
    UNIQUE_STAGES_REACHED NUMBER(38,0),
    MAX_STAGE_ORDINAL NUMBER(38,0),
    LAST_ENGAGEMENT_DAYS_AGO NUMBER(38,0),
    HAS_CLICKED BOOLEAN,
    DAYS_IN_JOURNEY NUMBER(38,0),
    DAYS_SINCE_LAST_OPEN NUMBER(38,0),
    ENGAGEMENT_DECLINE_FLAG BOOLEAN,
    CONVERTED_FLAG BOOLEAN,
    JOURNEY_DROPPED_FLAG BOOLEAN,
    EMAIL_FATIGUED_FLAG BOOLEAN
);

CREATE OR REPLACE TABLE FIPSAR_AI.AI_FEATURES.FEAT_UC03_SEND_TIME (
    MASTER_PATIENT_ID VARCHAR(20) NOT NULL,
    SEND_HOUR NUMBER(38,0) NOT NULL,
    DAY_OF_WEEK VARCHAR(10),
    IS_WEEKEND BOOLEAN,
    SENDS_AT_HOUR NUMBER(38,0),
    OPENS_AT_HOUR NUMBER(38,0),
    CLICKS_AT_HOUR NUMBER(38,0),
    OPEN_RATE_AT_HOUR FLOAT,
    CLICK_RATE_AT_HOUR FLOAT,
    AGE_GROUP VARCHAR(20),
    REGION VARCHAR(50),
    PRIMARY_CHANNEL VARCHAR(50),
    TOTAL_SENDS_ALLHOURS NUMBER(38,0),
    TOTAL_OPENS_ALLHOURS NUMBER(38,0),
    OVERALL_OPEN_RATE FLOAT,
    HOUR_VS_AVG_LIFT FLOAT,
    BEST_HOUR_FLAG BOOLEAN
);

CREATE OR REPLACE TABLE FIPSAR_AI.AI_FEATURES.TEST_UCA_PROSPECT_360 (
    MASTER_PATIENT_ID VARCHAR(20) NOT NULL,
    AGE NUMBER(38,0),
    AGE_GROUP VARCHAR(20),
    STATE VARCHAR(10),
    REGION VARCHAR(50),
    PRIMARY_CHANNEL VARCHAR(50),
    INTAKE_COUNT NUMBER(38,0),
    DAYS_SINCE_FIRST_INTAKE NUMBER(38,0),
    TOTAL_SENDS NUMBER(38,0),
    TOTAL_OPENS NUMBER(38,0),
    TOTAL_CLICKS NUMBER(38,0),
    TOTAL_BOUNCES NUMBER(38,0),
    TOTAL_UNSUBS NUMBER(38,0),
    OPEN_RATE FLOAT,
    CLICK_TO_OPEN_RATE FLOAT,
    UNIQUE_STAGES_REACHED NUMBER(38,0),
    MAX_STAGE_ORDINAL NUMBER(38,0),
    LAST_ENGAGEMENT_DAYS_AGO NUMBER(38,0),
    HAS_CLICKED BOOLEAN,
    DAYS_IN_JOURNEY NUMBER(38,0),
    DAYS_SINCE_LAST_OPEN NUMBER(38,0),
    ENGAGEMENT_DECLINE_FLAG BOOLEAN,
    CONVERTED_FLAG BOOLEAN,
    JOURNEY_DROPPED_FLAG BOOLEAN,
    EMAIL_FATIGUED_FLAG BOOLEAN,
    FEATURE_BUILT_AT TIMESTAMP_NTZ(9)
);

ALTER TABLE FIPSAR_AI.AI_FEATURES.TEST_UCA_PROSPECT_360 SET CHANGE_TRACKING = TRUE;

CREATE OR REPLACE TABLE FIPSAR_AI.AI_FEATURES.TEST_UC03_SEND_TIME (
    MASTER_PATIENT_ID VARCHAR(20) NOT NULL,
    SEND_HOUR NUMBER(38,0) NOT NULL,
    DAY_OF_WEEK VARCHAR(10),
    IS_WEEKEND BOOLEAN,
    SENDS_AT_HOUR NUMBER(38,0),
    OPENS_AT_HOUR NUMBER(38,0),
    CLICKS_AT_HOUR NUMBER(38,0),
    OPEN_RATE_AT_HOUR FLOAT,
    CLICK_RATE_AT_HOUR FLOAT,
    AGE_GROUP VARCHAR(20),
    REGION VARCHAR(50),
    PRIMARY_CHANNEL VARCHAR(50),
    TOTAL_SENDS_ALLHOURS NUMBER(38,0),
    TOTAL_OPENS_ALLHOURS NUMBER(38,0),
    OVERALL_OPEN_RATE FLOAT,
    HOUR_VS_AVG_LIFT FLOAT,
    BEST_HOUR_FLAG BOOLEAN,
    FEATURE_BUILT_AT TIMESTAMP_NTZ(9)
);

ALTER TABLE FIPSAR_AI.AI_FEATURES.TEST_UC03_SEND_TIME SET CHANGE_TRACKING = TRUE;

-- ── FIPSAR_AI.AI_SEMANTIC ──────────────────────────────────────────

CREATE OR REPLACE TABLE FIPSAR_AI.AI_SEMANTIC.AI_RUN_DETAILS (
    RUN_ID VARCHAR(50) NOT NULL,
    MODEL_VERSION VARCHAR(20),
    SCORED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    TOTAL_PROSPECTS_SCORED NUMBER(38,0),
    AUC_ROC VARIANT
);

CREATE OR REPLACE TABLE FIPSAR_AI.AI_SEMANTIC.HIST_AI_RUN_DETAILS (
    RUN_ID VARCHAR(50) NOT NULL,
    MODEL_VERSION VARCHAR(20),
    SCORED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    TOTAL_PROSPECTS_SCORED NUMBER(38,0),
    AUC_ROC VARIANT
);

CREATE OR REPLACE TABLE FIPSAR_AI.AI_SEMANTIC.HIST_UCB_SIGNAL_TRUST_SCORES (
    ENGAGEMENT_KEY NUMBER(38,0) NOT NULL,
    SUBSCRIBER_KEY VARCHAR(20),
    MASTER_PATIENT_ID VARCHAR(20),
    JOB_ID NUMBER(38,0),
    EVENT_TYPE VARCHAR(50),
    BOT_PROBABILITY FLOAT,
    IS_BOT_FLAG BOOLEAN,
    IS_ANOMALY BOOLEAN,
    ANOMALY_SEVERITY VARCHAR(10),
    ANOMALY_TYPE VARCHAR(50),
    BEST_SEND_HOUR NUMBER(38,0),
    BEST_SEND_DAY VARCHAR(10),
    TRUST_SCORE FLOAT,
    SCORED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    MODEL_VERSION VARCHAR(20),
    RUN_ID VARCHAR(50)
);

CREATE OR REPLACE TABLE FIPSAR_AI.AI_SEMANTIC.HIST_UCA_PROSPECT_360_SCORES (
    MASTER_PATIENT_ID VARCHAR(20) NOT NULL,
    CONVERSION_PROBABILITY FLOAT,
    CONVERSION_RISK_TIER VARCHAR(10),
    DROPOFF_PROBABILITY FLOAT,
    DROPOFF_RISK_TIER VARCHAR(10),
    FATIGUE_SCORE FLOAT,
    IS_FATIGUED BOOLEAN,
    CLUSTER_SEGMENT_ID NUMBER(38,0),
    CLUSTER_LABEL VARCHAR(50),
    SEND_STATUS VARCHAR(20),
    COMPOSITE_HEALTH_SCORE FLOAT,
    RECOMMENDED_ACTION VARCHAR(200),
    SCORED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    MODEL_VERSION VARCHAR(20),
    RUN_ID VARCHAR(50)
);

CREATE OR REPLACE TABLE FIPSAR_AI.AI_SEMANTIC.HIST_UC03_SEND_TIME_SCORES (
    MASTER_PATIENT_ID VARCHAR(20) NOT NULL,
    BEST_SEND_HOUR NUMBER(38,0),
    BEST_SEND_DAY VARCHAR(10),
    BEST_SEND_WINDOW VARCHAR(50),
    PREDICTED_OPEN_RATE FLOAT,
    BASELINE_OPEN_RATE FLOAT,
    ENGAGEMENT_LIFT FLOAT,
    CONFIDENCE_FLAG VARCHAR(10),
    SCORED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    MODEL_VERSION VARCHAR(20),
    RUN_ID VARCHAR(50)
);

CREATE OR REPLACE TABLE FIPSAR_AI.AI_SEMANTIC.SEM_UCB_SIGNAL_TRUST_SCORES (
    ENGAGEMENT_KEY NUMBER(38,0) NOT NULL,
    SUBSCRIBER_KEY VARCHAR(20),
    MASTER_PATIENT_ID VARCHAR(20),
    JOB_ID NUMBER(38,0),
    EVENT_TYPE VARCHAR(50),
    BOT_PROBABILITY FLOAT,
    IS_BOT_FLAG BOOLEAN,
    IS_ANOMALY BOOLEAN,
    ANOMALY_SEVERITY VARCHAR(10),
    ANOMALY_TYPE VARCHAR(50),
    BEST_SEND_HOUR NUMBER(38,0),
    BEST_SEND_DAY VARCHAR(10),
    TRUST_SCORE FLOAT,
    SCORED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    MODEL_VERSION VARCHAR(20),
    RUN_ID VARCHAR(50)
);

CREATE OR REPLACE TABLE FIPSAR_AI.AI_SEMANTIC.SEM_UCA_PROSPECT_360_SCORES (
    MASTER_PATIENT_ID VARCHAR(20) NOT NULL,
    CONVERSION_PROBABILITY FLOAT,
    CONVERSION_RISK_TIER VARCHAR(10),
    DROPOFF_PROBABILITY FLOAT,
    DROPOFF_RISK_TIER VARCHAR(10),
    FATIGUE_SCORE FLOAT,
    IS_FATIGUED BOOLEAN,
    CLUSTER_SEGMENT_ID NUMBER(38,0),
    CLUSTER_LABEL VARCHAR(50),
    SEND_STATUS VARCHAR(20),
    COMPOSITE_HEALTH_SCORE FLOAT,
    RECOMMENDED_ACTION VARCHAR(200),
    SCORED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    MODEL_VERSION VARCHAR(20),
    RUN_ID VARCHAR(50)
);

CREATE OR REPLACE TABLE FIPSAR_AI.AI_SEMANTIC.SEM_UC03_SEND_TIME_SCORES (
    MASTER_PATIENT_ID VARCHAR(20) NOT NULL,
    BEST_SEND_HOUR NUMBER(38,0),
    BEST_SEND_DAY VARCHAR(10),
    BEST_SEND_WINDOW VARCHAR(50),
    PREDICTED_OPEN_RATE FLOAT,
    BASELINE_OPEN_RATE FLOAT,
    ENGAGEMENT_LIFT FLOAT,
    CONFIDENCE_FLAG VARCHAR(10),
    SCORED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    MODEL_VERSION VARCHAR(20),
    RUN_ID VARCHAR(50)
);

-- ── FIPSAR_AUDIT.PIPELINE_AUDIT ────────────────────────────────────

CREATE OR REPLACE TABLE FIPSAR_AUDIT.PIPELINE_AUDIT.PIPELINE_RUN_LOG (
    RUN_ID VARCHAR(50) DEFAULT UUID_STRING(),
    PIPELINE_NAME VARCHAR(200) NOT NULL,
    LAYER VARCHAR(50) NOT NULL,
    TABLE_NAME VARCHAR(200),
    STATUS VARCHAR(20) NOT NULL,
    ROWS_LOADED NUMBER(38,0) DEFAULT 0,
    ROWS_REJECTED NUMBER(38,0) DEFAULT 0,
    ERROR_MESSAGE VARCHAR(4000),
    STARTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT TIMESTAMP_NTZ(9)
);

CREATE OR REPLACE TABLE FIPSAR_AUDIT.PIPELINE_AUDIT.DQ_REJECTION_LOG (
    REJECTION_ID VARCHAR(50) DEFAULT UUID_STRING(),
    TABLE_NAME VARCHAR(200) NOT NULL,
    REJECTION_REASON VARCHAR(500) NOT NULL,
    REJECTED_RECORD VARIANT,
    REJECTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FIPSAR_AUDIT.PIPELINE_AUDIT.SFMC_FILE_LOAD_AUDIT (
    RUN_ID VARCHAR(50),
    ENTITY_NAME VARCHAR(200),
    STAGE_NAME VARCHAR(500),
    TARGET_TABLE_NAME VARCHAR(200),
    FILE_NAME VARCHAR(1000),
    FILE_TIMESTAMP TIMESTAMP_NTZ(9),
    STATUS VARCHAR(20),
    ROWS_LOADED NUMBER(38,0),
    ERROR_MESSAGE VARCHAR(4000),
    STARTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT TIMESTAMP_NTZ(9)
);

-- ── QA TABLES (mirror PROD structure) ──────────────────────────────
-- QA databases mirror PROD table structures exactly.
-- Repeat all PROD table DDLs above, replacing database prefix with QA_

CREATE OR REPLACE TABLE QA_FIPSAR_PHI_HUB.STAGING.STG_PROSPECT_INTAKE LIKE FIPSAR_PHI_HUB.STAGING.STG_PROSPECT_INTAKE;
CREATE OR REPLACE TABLE QA_FIPSAR_PHI_HUB.PHI_CORE.PATIENT_IDENTITY_XREF LIKE FIPSAR_PHI_HUB.PHI_CORE.PATIENT_IDENTITY_XREF;
CREATE OR REPLACE TABLE QA_FIPSAR_PHI_HUB.PHI_CORE.PHI_PROSPECT_MASTER LIKE FIPSAR_PHI_HUB.PHI_CORE.PHI_PROSPECT_MASTER;
CREATE OR REPLACE TABLE QA_FIPSAR_DW.BRONZE.BRZ_PROSPECT_MASTER LIKE FIPSAR_DW.BRONZE.BRZ_PROSPECT_MASTER;
CREATE OR REPLACE TABLE QA_FIPSAR_DW.SILVER.SLV_PROSPECT_MASTER LIKE FIPSAR_DW.SILVER.SLV_PROSPECT_MASTER;
CREATE OR REPLACE TABLE QA_FIPSAR_DW.GOLD.DIM_CHANNEL LIKE FIPSAR_DW.GOLD.DIM_CHANNEL;
CREATE OR REPLACE TABLE QA_FIPSAR_DW.GOLD.DIM_DATE LIKE FIPSAR_DW.GOLD.DIM_DATE;
CREATE OR REPLACE TABLE QA_FIPSAR_DW.GOLD.DIM_ENGAGEMENT_TYPE LIKE FIPSAR_DW.GOLD.DIM_ENGAGEMENT_TYPE;
CREATE OR REPLACE TABLE QA_FIPSAR_DW.GOLD.DIM_GEOGRAPHY LIKE FIPSAR_DW.GOLD.DIM_GEOGRAPHY;
CREATE OR REPLACE TABLE QA_FIPSAR_DW.GOLD.DIM_PROSPECT LIKE FIPSAR_DW.GOLD.DIM_PROSPECT;
CREATE OR REPLACE TABLE QA_FIPSAR_DW.GOLD.DIM_SFMC_JOB LIKE FIPSAR_DW.GOLD.DIM_SFMC_JOB;
CREATE OR REPLACE TABLE QA_FIPSAR_DW.GOLD.FACT_PROSPECT_INTAKE LIKE FIPSAR_DW.GOLD.FACT_PROSPECT_INTAKE;
CREATE OR REPLACE TABLE QA_FIPSAR_DW.GOLD.FACT_SFMC_ENGAGEMENT LIKE FIPSAR_DW.GOLD.FACT_SFMC_ENGAGEMENT;
CREATE OR REPLACE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_SENT LIKE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_SENT;
CREATE OR REPLACE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_OPENS LIKE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_OPENS;
CREATE OR REPLACE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_CLICKS LIKE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_CLICKS;
CREATE OR REPLACE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_BOUNCES LIKE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_BOUNCES;
CREATE OR REPLACE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_UNSUBSCRIBES LIKE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_UNSUBSCRIBES;
CREATE OR REPLACE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_SPAM LIKE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_SPAM;
CREATE OR REPLACE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_JOB_METADATA LIKE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_JOB_METADATA;
CREATE OR REPLACE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_PROSPECT_C LIKE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_PROSPECT_C;
CREATE OR REPLACE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_PROSPECT_C_HISTORY LIKE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_PROSPECT_C_HISTORY;
CREATE OR REPLACE TABLE QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_PROSPECT_JOURNEY_DETAILS LIKE FIPSAR_SFMC_EVENTS.RAW_EVENTS.RAW_SFMC_PROSPECT_JOURNEY_DETAILS;
CREATE OR REPLACE TABLE QA_FIPSAR_AI.AI_FEATURES.FEAT_UCA_PROSPECT_360 LIKE FIPSAR_AI.AI_FEATURES.FEAT_UCA_PROSPECT_360;
CREATE OR REPLACE TABLE QA_FIPSAR_AI.AI_FEATURES.FEAT_UC03_SEND_TIME LIKE FIPSAR_AI.AI_FEATURES.FEAT_UC03_SEND_TIME;
CREATE OR REPLACE TABLE QA_FIPSAR_AI.AI_FEATURES.TEST_UCA_PROSPECT_360 LIKE FIPSAR_AI.AI_FEATURES.TEST_UCA_PROSPECT_360;
ALTER TABLE QA_FIPSAR_AI.AI_FEATURES.TEST_UCA_PROSPECT_360 SET CHANGE_TRACKING = TRUE;
CREATE OR REPLACE TABLE QA_FIPSAR_AI.AI_FEATURES.TEST_UC03_SEND_TIME LIKE FIPSAR_AI.AI_FEATURES.TEST_UC03_SEND_TIME;
ALTER TABLE QA_FIPSAR_AI.AI_FEATURES.TEST_UC03_SEND_TIME SET CHANGE_TRACKING = TRUE;
CREATE OR REPLACE TABLE QA_FIPSAR_AI.AI_SEMANTIC.AI_RUN_DETAILS LIKE FIPSAR_AI.AI_SEMANTIC.AI_RUN_DETAILS;
CREATE OR REPLACE TABLE QA_FIPSAR_AI.AI_SEMANTIC.HIST_AI_RUN_DETAILS LIKE FIPSAR_AI.AI_SEMANTIC.HIST_AI_RUN_DETAILS;
CREATE OR REPLACE TABLE QA_FIPSAR_AI.AI_SEMANTIC.HIST_UCB_SIGNAL_TRUST_SCORES LIKE FIPSAR_AI.AI_SEMANTIC.HIST_UCB_SIGNAL_TRUST_SCORES;
CREATE OR REPLACE TABLE QA_FIPSAR_AI.AI_SEMANTIC.HIST_UCA_PROSPECT_360_SCORES LIKE FIPSAR_AI.AI_SEMANTIC.HIST_UCA_PROSPECT_360_SCORES;
CREATE OR REPLACE TABLE QA_FIPSAR_AI.AI_SEMANTIC.HIST_UC03_SEND_TIME_SCORES LIKE FIPSAR_AI.AI_SEMANTIC.HIST_UC03_SEND_TIME_SCORES;
CREATE OR REPLACE TABLE QA_FIPSAR_AI.AI_SEMANTIC.SEM_UCB_SIGNAL_TRUST_SCORES LIKE FIPSAR_AI.AI_SEMANTIC.SEM_UCB_SIGNAL_TRUST_SCORES;
CREATE OR REPLACE TABLE QA_FIPSAR_AI.AI_SEMANTIC.SEM_UCA_PROSPECT_360_SCORES LIKE FIPSAR_AI.AI_SEMANTIC.SEM_UCA_PROSPECT_360_SCORES;
CREATE OR REPLACE TABLE QA_FIPSAR_AI.AI_SEMANTIC.SEM_UC03_SEND_TIME_SCORES LIKE FIPSAR_AI.AI_SEMANTIC.SEM_UC03_SEND_TIME_SCORES;
CREATE OR REPLACE TABLE QA_FIPSAR_AUDIT.PIPELINE_AUDIT.PIPELINE_RUN_LOG LIKE FIPSAR_AUDIT.PIPELINE_AUDIT.PIPELINE_RUN_LOG;
CREATE OR REPLACE TABLE QA_FIPSAR_AUDIT.PIPELINE_AUDIT.DQ_REJECTION_LOG LIKE FIPSAR_AUDIT.PIPELINE_AUDIT.DQ_REJECTION_LOG;
CREATE OR REPLACE TABLE QA_FIPSAR_AUDIT.PIPELINE_AUDIT.SFMC_FILE_LOAD_AUDIT LIKE FIPSAR_AUDIT.PIPELINE_AUDIT.SFMC_FILE_LOAD_AUDIT;


-- =====================================================================
-- 9. VIEWS
-- =====================================================================

CREATE OR REPLACE VIEW FIPSAR_DW.GOLD.VW_SFMC_PROSPECT_OUTBOUND (
    PROSPECTID, FIRSTNAME, LASTNAME, EMAILADDRESS,
    MARKETINGCONSENT, HIGHENGAGEMENT, REGISTRATIONDATE
) AS
SELECT
    dp.MASTER_PATIENT_ID AS ProspectID,
    dp.FIRST_NAME AS FirstName,
    dp.LAST_NAME AS LastName,
    dp.EMAIL AS EmailAddress,
    dp.PATIENT_CONSENT AS MarketingConsent,
    TRUE AS HighEngagement,
    TO_VARCHAR(CURRENT_TIMESTAMP(), 'MM/DD/YYYY HH12:MI:SS AM') AS RegistrationDate
FROM FIPSAR_DW.GOLD.DIM_PROSPECT dp
WHERE dp.IS_ACTIVE = TRUE
  AND dp.PATIENT_CONSENT = TRUE
  AND NULLIF(TRIM(dp.EMAIL), '') IS NOT NULL
  AND UPPER(TRIM(dp.EMAIL)) <> 'N/A';

-- VW_MART_JOURNEY_INTELLIGENCE is a large analytical view (~10KB).
-- Extract its full DDL with:
--   SELECT GET_DDL('VIEW', 'FIPSAR_DW.GOLD.VW_MART_JOURNEY_INTELLIGENCE');


-- =====================================================================
-- 10. STREAMS
-- =====================================================================

-- ── PROD ─────────────────────────────────────────────────────────────

CREATE OR REPLACE STREAM FIPSAR_AI.AI_FEATURES.STREAM_ENGAGEMENT
    ON TABLE FIPSAR_DW.GOLD.FACT_SFMC_ENGAGEMENT
    APPEND_ONLY = TRUE
    COMMENT = 'Detects new SFMC engagement events';

CREATE OR REPLACE STREAM FIPSAR_AI.AI_FEATURES.STREAM_PROSPECT
    ON TABLE FIPSAR_DW.GOLD.DIM_PROSPECT
    COMMENT = 'Detects new or updated prospects';

CREATE OR REPLACE STREAM FIPSAR_AI.AI_FEATURES.STREAM_TEST_UCA
    ON TABLE FIPSAR_AI.AI_FEATURES.TEST_UCA_PROSPECT_360
    APPEND_ONLY = TRUE
    COMMENT = 'Detects new test feature rows for Prospect 360';

CREATE OR REPLACE STREAM FIPSAR_AI.AI_FEATURES.STREAM_TEST_UC03
    ON TABLE FIPSAR_AI.AI_FEATURES.TEST_UC03_SEND_TIME
    APPEND_ONLY = TRUE
    COMMENT = 'Detects new test feature rows for Send Time';

-- ── QA ───────────────────────────────────────────────────────────────

CREATE OR REPLACE STREAM QA_FIPSAR_AI.AI_FEATURES.STREAM_ENGAGEMENT
    ON TABLE FIPSAR_DW.GOLD.FACT_SFMC_ENGAGEMENT
    APPEND_ONLY = TRUE
    COMMENT = 'Detects new SFMC engagement events';

CREATE OR REPLACE STREAM QA_FIPSAR_AI.AI_FEATURES.STREAM_PROSPECT
    ON TABLE FIPSAR_DW.GOLD.DIM_PROSPECT
    COMMENT = 'Detects new or updated prospects';

CREATE OR REPLACE STREAM QA_FIPSAR_AI.AI_FEATURES.STREAM_TEST_UCA
    ON TABLE QA_FIPSAR_AI.AI_FEATURES.TEST_UCA_PROSPECT_360
    APPEND_ONLY = TRUE
    COMMENT = 'Detects new test feature rows for Prospect 360';

CREATE OR REPLACE STREAM QA_FIPSAR_AI.AI_FEATURES.STREAM_TEST_UC03
    ON TABLE QA_FIPSAR_AI.AI_FEATURES.TEST_UC03_SEND_TIME
    APPEND_ONLY = TRUE
    COMMENT = 'Detects new test feature rows for Send Time';


-- =====================================================================
-- 11. STORED PROCEDURES
-- =====================================================================
-- Stored procedures contain complex pipeline logic and are too large
-- to embed inline (~60+ procedures totaling 100KB+).
-- Use the self-extracting DDL helper below to regenerate them.
--
-- PROD Procedures (user-defined):
-- ┌──────────────────────────────────────────────────────────────┐
-- │ FIPSAR_PHI_HUB.PHI_CORE                                     │
-- │   SP_LOAD_STAGING_FROM_S3()                                  │
-- │   SP_LOAD_PHI_PROSPECT()                                     │
-- ├──────────────────────────────────────────────────────────────┤
-- │ FIPSAR_DW.BRONZE                                             │
-- │   SP_LOAD_BRONZE_PROSPECT()                                  │
-- ├──────────────────────────────────────────────────────────────┤
-- │ FIPSAR_DW.SILVER                                             │
-- │   SP_LOAD_SILVER_PROSPECT()                                  │
-- ├──────────────────────────────────────────────────────────────┤
-- │ FIPSAR_DW.GOLD                                               │
-- │   SP_LOAD_GOLD_DIM_PROSPECT()                                │
-- │   SP_LOAD_GOLD_FACT_INTAKE()                                 │
-- │   SP_EXPORT_SFMC_OUTBOUND()                                  │
-- ├──────────────────────────────────────────────────────────────┤
-- │ FIPSAR_AUDIT.PIPELINE_AUDIT                                  │
-- │   SP_SEND_SILVER_DQ_STATUS_EMAIL()                           │
-- ├──────────────────────────────────────────────────────────────┤
-- │ FIPSAR_SFMC_EVENTS.RAW_EVENTS                                │
-- │   SP_LOAD_RAW_SFMC_SENT()                                    │
-- │   SP_LOAD_RAW_SFMC_OPENS()                                   │
-- │   SP_LOAD_RAW_SFMC_CLICKS()                                  │
-- │   SP_LOAD_RAW_SFMC_BOUNCES()                                 │
-- │   SP_LOAD_RAW_SFMC_UNSUBSCRIBES()                            │
-- │   SP_LOAD_RAW_SFMC_SPAM()                                    │
-- │   SP_LOAD_RAW_SFMC_JOB_METADATA()                            │
-- │   SP_LOAD_RAW_SFMC_JOB_DE_DETAIL()                           │
-- │   SP_LOAD_RAW_SFMC_UNSUBSCRIBE_DE_DETAIL()                   │
-- │   SP_LOAD_RAW_SFMC_JOURNEY_ACTIVITY_GENERIC()                │
-- │   SP_LOAD_RAW_SFMC_PROSPECT_C()                              │
-- │   SP_LOAD_RAW_SFMC_PROSPECT_C_HISTORY()                      │
-- │   SP_LOAD_RAW_SFMC_PROSPECT_JOURNEY_DETAILS()                │
-- │   SP_LOAD_SFMC_JOB_METADATA()                                │
-- │   SP_LOAD_GOLD_FACT_ENGAGEMENT()                              │
-- │   SP_PROCESS_SFMC_SUPPRESSION()                               │
-- │   SP_COPY_NEW_FILES(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR) │
-- │   SP_RUN_SFMC_EVENTS_PIPELINE()                               │
-- ├──────────────────────────────────────────────────────────────┤
-- │ FIPSAR_AI.AI_PIPELINES                                       │
-- │   RUN_SIGNAL_TRUST(VARCHAR)                                   │
-- │   RUN_PROSPECT360(VARCHAR)                                    │
-- │   RUN_SEND_TIME(VARCHAR)                                      │
-- │   REFRESH_CURRENT_TABLES(VARCHAR)                             │
-- │   BUILD_UCA_TEST_FEATURES(VARCHAR)                            │
-- │   BUILD_UC03_TEST_FEATURES(VARCHAR)                           │
-- │   RUN_FULL_PIPELINE()                                         │
-- └──────────────────────────────────────────────────────────────┘
--
-- QA databases share the same procedure code pointing to PROD references
-- (they were cloned from PROD). Re-extract with the helper below.

-- ═══════════════════════════════════════════════════════════════════
-- SELF-EXTRACTING PROCEDURE DDL HELPER
-- Run this query to generate CREATE OR REPLACE statements for ALL
-- user-defined stored procedures in the account:
-- ═══════════════════════════════════════════════════════════════════
/*
SELECT
    p."catalog_name" || '.' || p."schema_name" || '.' || p."name" || '(' ||
    COALESCE(LISTAGG(dt.VALUE::STRING, ', ') WITHIN GROUP (ORDER BY dt.INDEX), '') ||
    ')' AS proc_signature,
    GET_DDL('PROCEDURE',
        p."catalog_name" || '.' || p."schema_name" || '.' || p."name" || '(' ||
        COALESCE(LISTAGG(dt.VALUE::STRING, ', ') WITHIN GROUP (ORDER BY dt.INDEX), '') ||
        ')'
    ) AS ddl
FROM (
    SELECT * FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
) p,
LATERAL FLATTEN(INPUT => SPLIT(
    REGEXP_SUBSTR(p."arguments", '\\((.*)\\)', 1, 1, 'e', 1), ', '
), OUTER => TRUE) dt
WHERE p."is_builtin" = 'N'
GROUP BY p."catalog_name", p."schema_name", p."name", p."arguments";

-- OR individually, one at a time:
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_PHI_HUB.PHI_CORE.SP_LOAD_STAGING_FROM_S3()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_PHI_HUB.PHI_CORE.SP_LOAD_PHI_PROSPECT()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_DW.BRONZE.SP_LOAD_BRONZE_PROSPECT()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_DW.SILVER.SP_LOAD_SILVER_PROSPECT()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_DW.GOLD.SP_LOAD_GOLD_DIM_PROSPECT()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_DW.GOLD.SP_LOAD_GOLD_FACT_INTAKE()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_DW.GOLD.SP_EXPORT_SFMC_OUTBOUND()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_AUDIT.PIPELINE_AUDIT.SP_SEND_SILVER_DQ_STATUS_EMAIL()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_LOAD_RAW_SFMC_SENT()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_LOAD_RAW_SFMC_OPENS()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_LOAD_RAW_SFMC_CLICKS()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_LOAD_RAW_SFMC_BOUNCES()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_LOAD_RAW_SFMC_UNSUBSCRIBES()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_LOAD_RAW_SFMC_SPAM()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_LOAD_RAW_SFMC_JOB_METADATA()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_LOAD_RAW_SFMC_JOB_DE_DETAIL()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_LOAD_RAW_SFMC_UNSUBSCRIBE_DE_DETAIL()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_LOAD_RAW_SFMC_JOURNEY_ACTIVITY_GENERIC()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_LOAD_RAW_SFMC_PROSPECT_C()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_LOAD_RAW_SFMC_PROSPECT_C_HISTORY()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_LOAD_RAW_SFMC_PROSPECT_JOURNEY_DETAILS()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_LOAD_SFMC_JOB_METADATA()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_LOAD_GOLD_FACT_ENGAGEMENT()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_PROCESS_SFMC_SUPPRESSION()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_COPY_NEW_FILES(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR)');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_RUN_SFMC_EVENTS_PIPELINE()');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_AI.AI_PIPELINES.RUN_SIGNAL_TRUST(VARCHAR)');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_AI.AI_PIPELINES.RUN_PROSPECT360(VARCHAR)');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_AI.AI_PIPELINES.RUN_SEND_TIME(VARCHAR)');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_AI.AI_PIPELINES.REFRESH_CURRENT_TABLES(VARCHAR)');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_AI.AI_PIPELINES.BUILD_UCA_TEST_FEATURES(VARCHAR)');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_AI.AI_PIPELINES.BUILD_UC03_TEST_FEATURES(VARCHAR)');
-- SELECT GET_DDL('PROCEDURE', 'FIPSAR_AI.AI_PIPELINES.RUN_FULL_PIPELINE()');
*/


-- =====================================================================
-- 12. TASKS
-- =====================================================================

-- ── PROD: FIPSAR_PHI_HUB Pipeline (DAG) ────────────────────────────
-- Execution order: ORCHESTRATOR → PHI_IDENTITY → BRONZE → SILVER
--   → {GOLD_LOAD, SILVER_DQ_NOTIFICATION}
--   → SFMC_OUTBOUND_EXPORT → PIPELINE_NOTIFICATION

CREATE OR REPLACE TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_PHI_ORCHESTRATOR
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'ROOT: Load S3 CSVs into PHI staging'
AS
    CALL FIPSAR_PHI_HUB.PHI_CORE.SP_LOAD_STAGING_FROM_S3();

CREATE OR REPLACE TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_PHI_IDENTITY_LOAD
    WAREHOUSE = COMPUTE_WH
    AFTER FIPSAR_PHI_HUB.PHI_CORE.TASK_PHI_ORCHESTRATOR
    COMMENT = 'Assign MASTER_PATIENT_ID and load PHI table'
AS
    CALL FIPSAR_PHI_HUB.PHI_CORE.SP_LOAD_PHI_PROSPECT();

CREATE OR REPLACE TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_BRONZE_LOAD
    WAREHOUSE = COMPUTE_WH
    AFTER FIPSAR_PHI_HUB.PHI_CORE.TASK_PHI_IDENTITY_LOAD
    COMMENT = 'Raw copy PHI → Bronze'
AS
    CALL FIPSAR_DW.BRONZE.SP_LOAD_BRONZE_PROSPECT();

CREATE OR REPLACE TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_SILVER_LOAD
    WAREHOUSE = COMPUTE_WH
    AFTER FIPSAR_PHI_HUB.PHI_CORE.TASK_BRONZE_LOAD
    COMMENT = 'DQ gates: null rejection + dedup + SCD2 → Silver'
AS
    CALL FIPSAR_DW.SILVER.SP_LOAD_SILVER_PROSPECT();

CREATE OR REPLACE TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_SILVER_DQ_NOTIFICATION
    WAREHOUSE = COMPUTE_WH
    AFTER FIPSAR_PHI_HUB.PHI_CORE.TASK_SILVER_LOAD
    COMMENT = 'Send PHI/Bronze/Silver status + DQ summary email'
AS
    CALL FIPSAR_AUDIT.PIPELINE_AUDIT.SP_SEND_SILVER_DQ_STATUS_EMAIL();

CREATE OR REPLACE TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_GOLD_LOAD
    WAREHOUSE = COMPUTE_WH
    AFTER FIPSAR_PHI_HUB.PHI_CORE.TASK_SILVER_LOAD
    COMMENT = 'Load Gold dimensions and facts'
AS
    BEGIN
        CALL FIPSAR_DW.GOLD.SP_LOAD_GOLD_DIM_PROSPECT();
        CALL FIPSAR_DW.GOLD.SP_LOAD_GOLD_FACT_INTAKE();
    END;

CREATE OR REPLACE TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_SFMC_OUTBOUND_EXPORT
    WAREHOUSE = COMPUTE_WH
    AFTER FIPSAR_PHI_HUB.PHI_CORE.TASK_GOLD_LOAD
    COMMENT = 'Export prospect delta CSV to S3 for SFMC (Prospect_c_delta_YYYYMMDD_HHMM.csv)'
AS
    CALL FIPSAR_DW.GOLD.SP_EXPORT_SFMC_OUTBOUND();

CREATE OR REPLACE TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_PIPELINE_NOTIFICATION
    WAREHOUSE = COMPUTE_WH
    AFTER FIPSAR_PHI_HUB.PHI_CORE.TASK_SFMC_OUTBOUND_EXPORT
    COMMENT = 'Send pipeline completion email'
AS
    CALL SYSTEM$SEND_EMAIL(
        'FIPSAR_EMAIL_NOTIFICATION',
        'akileshvishnu103@gmail.com',
        'FIPSAR Pipeline Complete',
        'Full prospect pipeline (PHI → Bronze → Silver → Gold → SFMC Export) completed. Check FIPSAR_AUDIT.PIPELINE_AUDIT.PIPELINE_RUN_LOG for details.'
    );

-- ── PROD: FIPSAR_SFMC_EVENTS ───────────────────────────────────────

CREATE OR REPLACE TASK FIPSAR_SFMC_EVENTS.RAW_EVENTS.TASK_SFMC_EVENTS_LOAD
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Load SFMC event files from dedicated S3 folders every 4 hours'
AS
    CALL FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_RUN_SFMC_EVENTS_PIPELINE();

-- ── PROD: FIPSAR_AI ────────────────────────────────────────────────

CREATE OR REPLACE TASK FIPSAR_AI.AI_PIPELINES.TASK_RUN_FULL_PIPELINE
    WAREHOUSE = COMPUTE_WH
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Runs full AI pipeline when new Gold data arrives'
    WHEN SYSTEM$STREAM_HAS_DATA('FIPSAR_AI.AI_FEATURES.STREAM_ENGAGEMENT')
      OR SYSTEM$STREAM_HAS_DATA('FIPSAR_AI.AI_FEATURES.STREAM_PROSPECT')
AS
    CALL FIPSAR_AI.AI_PIPELINES.RUN_FULL_PIPELINE();

CREATE OR REPLACE TASK FIPSAR_AI.AI_PIPELINES.TASK_DAILY_PIPELINE
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 6 * * * America/New_York'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Daily 6 AM EST fallback run'
AS
    CALL FIPSAR_AI.AI_PIPELINES.RUN_FULL_PIPELINE();

-- ── QA: QA_FIPSAR_PHI_HUB Pipeline (DAG) ───────────────────────────

CREATE OR REPLACE TASK QA_FIPSAR_PHI_HUB.PHI_CORE.TASK_PHI_ORCHESTRATOR
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'ROOT: Load S3 CSVs into PHI staging'
AS
    CALL FIPSAR_PHI_HUB.PHI_CORE.SP_LOAD_STAGING_FROM_S3();

CREATE OR REPLACE TASK QA_FIPSAR_PHI_HUB.PHI_CORE.TASK_PHI_IDENTITY_LOAD
    WAREHOUSE = COMPUTE_WH
    AFTER QA_FIPSAR_PHI_HUB.PHI_CORE.TASK_PHI_ORCHESTRATOR
    COMMENT = 'Assign MASTER_PATIENT_ID and load PHI table'
AS
    CALL FIPSAR_PHI_HUB.PHI_CORE.SP_LOAD_PHI_PROSPECT();

CREATE OR REPLACE TASK QA_FIPSAR_PHI_HUB.PHI_CORE.TASK_BRONZE_LOAD
    WAREHOUSE = COMPUTE_WH
    AFTER QA_FIPSAR_PHI_HUB.PHI_CORE.TASK_PHI_IDENTITY_LOAD
    COMMENT = 'Raw copy PHI → Bronze'
AS
    CALL FIPSAR_DW.BRONZE.SP_LOAD_BRONZE_PROSPECT();

CREATE OR REPLACE TASK QA_FIPSAR_PHI_HUB.PHI_CORE.TASK_SILVER_LOAD
    WAREHOUSE = COMPUTE_WH
    AFTER QA_FIPSAR_PHI_HUB.PHI_CORE.TASK_BRONZE_LOAD
    COMMENT = 'DQ gates: null rejection + dedup + SCD2 → Silver'
AS
    CALL FIPSAR_DW.SILVER.SP_LOAD_SILVER_PROSPECT();

CREATE OR REPLACE TASK QA_FIPSAR_PHI_HUB.PHI_CORE.TASK_SILVER_DQ_NOTIFICATION
    WAREHOUSE = COMPUTE_WH
    AFTER QA_FIPSAR_PHI_HUB.PHI_CORE.TASK_SILVER_LOAD
    COMMENT = 'Send PHI/Bronze/Silver status + DQ summary email'
AS
    CALL FIPSAR_AUDIT.PIPELINE_AUDIT.SP_SEND_SILVER_DQ_STATUS_EMAIL();

CREATE OR REPLACE TASK QA_FIPSAR_PHI_HUB.PHI_CORE.TASK_GOLD_LOAD
    WAREHOUSE = COMPUTE_WH
    AFTER QA_FIPSAR_PHI_HUB.PHI_CORE.TASK_SILVER_LOAD
    COMMENT = 'Load Gold dimensions and facts'
AS
    BEGIN
        CALL FIPSAR_DW.GOLD.SP_LOAD_GOLD_DIM_PROSPECT();
        CALL FIPSAR_DW.GOLD.SP_LOAD_GOLD_FACT_INTAKE();
    END;

CREATE OR REPLACE TASK QA_FIPSAR_PHI_HUB.PHI_CORE.TASK_SFMC_OUTBOUND_EXPORT
    WAREHOUSE = COMPUTE_WH
    AFTER QA_FIPSAR_PHI_HUB.PHI_CORE.TASK_GOLD_LOAD
    COMMENT = 'Export prospect delta CSV to S3 for SFMC (Prospect_c_delta_YYYYMMDD_HHMM.csv)'
AS
    CALL FIPSAR_DW.GOLD.SP_EXPORT_SFMC_OUTBOUND();

CREATE OR REPLACE TASK QA_FIPSAR_PHI_HUB.PHI_CORE.TASK_PIPELINE_NOTIFICATION
    WAREHOUSE = COMPUTE_WH
    AFTER QA_FIPSAR_PHI_HUB.PHI_CORE.TASK_SFMC_OUTBOUND_EXPORT
    COMMENT = 'Send pipeline completion email'
AS
    CALL SYSTEM$SEND_EMAIL(
        'FIPSAR_EMAIL_NOTIFICATION',
        'akileshvishnu103@gmail.com',
        'FIPSAR Pipeline Complete',
        'Full prospect pipeline (PHI → Bronze → Silver → Gold → SFMC Export) completed. Check FIPSAR_AUDIT.PIPELINE_AUDIT.PIPELINE_RUN_LOG for details.'
    );

-- ── QA: QA_FIPSAR_SFMC_EVENTS ──────────────────────────────────────

CREATE OR REPLACE TASK QA_FIPSAR_SFMC_EVENTS.RAW_EVENTS.TASK_SFMC_EVENTS_LOAD
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Load SFMC event files from dedicated S3 folders every 4 hours'
AS
    CALL FIPSAR_SFMC_EVENTS.RAW_EVENTS.SP_RUN_SFMC_EVENTS_PIPELINE();

-- ── QA: QA_FIPSAR_AI ───────────────────────────────────────────────

CREATE OR REPLACE TASK QA_FIPSAR_AI.AI_PIPELINES.TASK_RUN_FULL_PIPELINE
    WAREHOUSE = COMPUTE_WH
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Runs full AI pipeline when new Gold data arrives'
    WHEN SYSTEM$STREAM_HAS_DATA('FIPSAR_AI.AI_FEATURES.STREAM_ENGAGEMENT')
      OR SYSTEM$STREAM_HAS_DATA('FIPSAR_AI.AI_FEATURES.STREAM_PROSPECT')
AS
    CALL FIPSAR_AI.AI_PIPELINES.RUN_FULL_PIPELINE();

CREATE OR REPLACE TASK QA_FIPSAR_AI.AI_PIPELINES.TASK_DAILY_PIPELINE
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 6 * * * America/New_York'
    ALLOW_OVERLAPPING_EXECUTION = FALSE
    COMMENT = 'Daily 6 AM EST fallback run'
AS
    CALL FIPSAR_AI.AI_PIPELINES.RUN_FULL_PIPELINE();

-- NOTE: All tasks are created in SUSPENDED state by default.
-- To resume the PROD pipeline, start from leaf to root:
--   ALTER TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_PIPELINE_NOTIFICATION RESUME;
--   ALTER TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_SFMC_OUTBOUND_EXPORT RESUME;
--   ALTER TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_SILVER_DQ_NOTIFICATION RESUME;
--   ALTER TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_GOLD_LOAD RESUME;
--   ALTER TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_SILVER_LOAD RESUME;
--   ALTER TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_BRONZE_LOAD RESUME;
--   ALTER TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_PHI_IDENTITY_LOAD RESUME;
--   ALTER TASK FIPSAR_PHI_HUB.PHI_CORE.TASK_PHI_ORCHESTRATOR RESUME;
--   ALTER TASK FIPSAR_SFMC_EVENTS.RAW_EVENTS.TASK_SFMC_EVENTS_LOAD RESUME;
--   ALTER TASK FIPSAR_AI.AI_PIPELINES.TASK_RUN_FULL_PIPELINE RESUME;
--   ALTER TASK FIPSAR_AI.AI_PIPELINES.TASK_DAILY_PIPELINE RESUME;


-- =====================================================================
-- 13. STREAMLIT APPS
-- =====================================================================
-- Streamlit app: FIPSAR_AI.AI_SEMANTIC.GWEQ0YVTMOPIBNXB
--   Title: "Fipsar Cortex App"
--   Warehouse: COMPUTE_WH
-- NOTE: Streamlit apps cannot be migrated via DDL.
--   Redeploy via Snowsight UI or Snowflake CLI.


-- =====================================================================
-- 14. VW_MART_JOURNEY_INTELLIGENCE (large view – extract separately)
-- =====================================================================
-- This view is ~10KB of SQL. Extract with:
--   SELECT GET_DDL('VIEW', 'FIPSAR_DW.GOLD.VW_MART_JOURNEY_INTELLIGENCE');


/***********************************************************************
 *  END OF DDL MIGRATION SCRIPT
 *  
 *  COMPLETE OBJECT CHECKLIST:
 *  ─────────────────────────────────────────────────────────────────
 *  [✓] 2 Warehouses (COMPUTE_WH, SYSTEM$STREAMLIT_NOTEBOOK_WH)
 *  [✓] 1 Storage Integration (FIPSAR_S3_INTEGRATION)
 *  [✓] 1 Notification Integration (FIPSAR_EMAIL_NOTIFICATION)
 *  [✓] 10 Databases (5 PROD + 5 QA)
 *  [✓] 20 Custom Schemas (excl. PUBLIC/INFORMATION_SCHEMA)
 *  [✓] 4 Sequences (2 PROD + 2 QA)
 *  [✓] 10 File Formats (5 PROD + 5 QA)
 *  [✓] 28 External Stages (14 PROD + 14 QA)
 *  [✓] 2 Internal Stages (CSV_UPLOAD_STAGE, CORTEX_ANALYST_STAGE)
 *  [✓] 33 PROD Tables + 39 QA Tables (via LIKE)
 *  [✓] 2 Views (VW_SFMC_PROSPECT_OUTBOUND, VW_MART_JOURNEY_INTELLIGENCE)
 *  [✓] 8 Streams (4 PROD + 4 QA)
 *  [✓] 27 User-Defined Stored Procedures (extract via helper)
 *  [✓] 22 Tasks (11 PROD + 11 QA)
 *  [✓] 1 Streamlit App (manual redeploy)
 *  [✓] 0 Pipes, 0 Alerts, 0 Dynamic Tables, 0 Masking Policies
 *  [✓] 0 Row Access Policies, 0 Network Policies, 0 Resource Monitors
 ***********************************************************************/
